openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operation about contacts.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-goit-hw-mongodb.onrender.com
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /contacts:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
    get:
      $ref: ../swagger/paths/contacts/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
